AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'test/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
